name: Compilar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Dar permisos
        run: chmod +x gradlew || true

      - name: Compilar APK
        run: gradle :app:assembleDebug

      - name: Preparar APK
        run: |
          mkdir -p apk
          cp app/build/outputs/apk/debug/app-debug.apk \
             "apk/Cuando_nosotros_eramos_jovenes.apk"

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: Cuando-nosotros-eramos-jovenes-APK
          path: apk/Cuando_nosotros_eramos_jovenes.apk
          if-no-files-found: error
